---
title: "Figure 2"
author: "Mitch Bobbin"
date: "2024-09-23"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(extrafont)
library(showtext)
library(sjPlot)
library(scales)
#adhering to style guide for SAFE/EC:
font_add_google("Raleway", "raleway")
showtext_auto()
setwd("C:/Users/Mitch/Documents/SAFE")

#monthly spot prices for wti crude from EIA
wti_oil<-read.csv("wti_oil_price.csv")

#FRED's endline GDP estimate in billions of dollars:
gdp_endline<-read.csv("gdp_endline_fred.csv")

#https://www.eia.gov/state/seds/data.php?incfile=/state/seds/sep_prices/tx/pr_tx_US.html&sid=US
#this gives us overall nominal expenditures on petroleum. We take the values manually and 
#place them into a df in R:

years <- c(1970, 1971, 1972, 1973, 1974, 1975, 1976, 1977, 1978, 1979, 
           1980, 1981, 1982, 1983, 1984, 1985, 1986, 1987, 1988, 1989, 
           1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 
           2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 
           2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 
           2020, 2021, 2022)
#expenditures are in millions of USD. Use the total column for petroleum:
expenditures <- c(47021, 50370, 53609, 62234, 90357, 97064, 108641, 122423, 129390, 173211, 
                  226248, 253165, 234676, 214365, 219496, 219546, 172288, 185171, 187691, 203528, 
                  233268, 221888, 220897, 221581, 228073, 235641, 266125, 265958, 229820, 262090, 
                  354595, 333218, 318523, 374419, 465315, 588736, 677552, 735133, 866011, 580967, 
                  713561, 891867, 880436, 876470, 860331, 621422, 548571, 630231, 740139, 698670, 
                  503607, 756676, 1048043)


petroleum_data <- data.frame(year = years, expenditures = expenditures)

library(lubridate)

#convert to datetime and extract year for when we combine dfs:
gdp_endline$DATE <- mdy(gdp_endline$DATE)
gdp_endline$DATE <- year(gdp_endline$DATE)

gdp_endline$GDP<-as.numeric(gdp_endline$GDP)

#looking at 1970 to present to understand oil price volatility's effect on economy. 
#oil not very volatile before this year.:
gdp_endline<-gdp_endline %>% 
  filter(DATE>=1970) %>% 
  rename(year=DATE)

wti_oil$date<-mdy(wti_oil$date)
wti_oil$year <- year(wti_oil$date)

#smooth prices over each year for consistent analysis:
wti_oil<-wti_oil %>% 
  group_by(year) %>% 
  summarize(avg_yearly_price=mean(price))

#merge dfs so we can look at petrol expenditures as a share of gdp
petroleum_data <- merge(petroleum_data, gdp_endline, by = "year")
petroleum_data <- merge(petroleum_data, wti_oil, by = "year")

#cpi from https://www.minneapolisfed.org/about-us/monetary-policy/inflation-calculator/consumer-price-index-1913-
#cpi needed to adjust oil prices to 2022 dollars.
cpi<-c(38.8,40.5,41.8,44.4,49.3,53.8,56.9,60.6,65.2,72.6,82.4,90.9,96.5,99.6,103.9,107.6,109.6,113.6,118.3,124,130.7,136.2,140.3,144.5,148.2,152.4,156.9,160.5,163.0,166.6,172.2,177.1,179.9,184,188.9,195.3,201.6,207.3,215.3,214.5,218.1,224.9,229.6,233.0,236.7,237,240,245.1,251.1,255.7,258.8,271,292.7)

petroleum_data$cpi<-cpi

#adjust each year's prices to 2022 dollars. this should show just how volatile
#prices are.
#expenditures do not need adjustment, since just doing percentage of gdp that were
#oil expenditures
petroleum_data<-petroleum_data %>% 
  mutate(inflation_adjuster=292.7/cpi, 
         adj_oil_price=inflation_adjuster*avg_yearly_price)

#need gdp and expenditures in same units. dividing by 1000 gives us expenditures in billions:
petroleum_data$expenditures<-petroleum_data$expenditures/1000

#now see the percentage of each year, and mark years where fed decided there was a #recession. Any year with a quarter where there was a recession gets the indicator:
petroleum_data<-petroleum_data %>% 
  mutate(perc_petrol=(expenditures/GDP)*100,
         recession = case_when(year%in%c(1970,1973,1974,1975,1980,1981,1982,1990,1991,2000,2001,2007,2008,2020)~1,
                               TRUE~0))


#create a scaling factor to display a dual axis plot:
petrol_scaling_factor<-max(petroleum_data$perc_petrol)/max(petroleum_data$adj_oil_price)

petrol_expenditures_oil_price<-petroleum_data %>% 
  ggplot(aes(x=year)) +
  geom_col(aes(y=perc_petrol, fill=factor(recession)), width = .5) +
  geom_line(aes(y=adj_oil_price*petrol_scaling_factor, color="Crude Oil Price,\nAdjusted for Inflation"), size=1) +
  scale_y_continuous(
    name = "Percent of GDP spent on Petroleum",
    labels = percent_format(scale = 1),
    breaks = seq(0, 8, by = 1),
    sec.axis = sec_axis(~./petrol_scaling_factor , name = "USD per Barrel, in 2022 Dollars",breaks = seq(0,140,by=20))
  ) +
  scale_x_continuous(breaks=seq(1970,2022,by=5)) +
  scale_fill_manual(
    values = c("0" = "#009BC9", "1" = "lightblue"),
    labels = c("0" = "Percent of GDP", "1" = "Percent of GDP during Recessionary Periods"),
    name = "Recession"
  ) +
  scale_color_manual(values = "#EF5A22", name = "Crude Oil Price,\nAdjusted for Inflation") +
  labs(
    x = "Year",
    title = "U.S. Crude Oil Prices, Petroleum Expenditures and Economic Recessions, 1970-2022",
    subtitle = "Source: Electrification Coalition analysis using data from FRED and EIA"
  ) +
  guides(
    fill = guide_legend(title = "",position = "bottom"),
    color = guide_legend(title = "",position="bottom")
  )+
  theme(
    text = element_text(size = 14),
    plot.title = element_text(size = 20, face = "bold",hjust = .5,color = "white"),
    plot.subtitle = element_text(size = 16,hjust=.5,color = "white",family="raleway"),
    axis.line = element_line(color = "#003554",size=1.5),
    axis.title = element_text(size = 14,color = "white",family="raleway"),
    axis.text = element_text(size = 14,color = "white",family="raleway"),
    legend.text = element_text(size = 12,color = "white",family="raleway",lineheight=.75),
    panel.background = element_rect(fill = "black"),
    plot.background = element_rect(fill = "black"), 
    legend.background = element_rect(fill = "black"), 
    panel.grid.major = element_line(color="lightgrey"),
    panel.grid.minor = element_blank(),
    panel.grid.major.x = element_blank(),
    axis.ticks = element_line(size = 1,color="white")
  )
ggsave(filename = "petrol_expenditures_oil_price.svg", plot = petrol_expenditures_oil_price, width=12, height=8)
```

